"use client";

import './styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StyledJsxRegistry from './registry'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <StyledJsxRegistry>
        <body className={inter.className}>{children}</body>
      </StyledJsxRegistry>
    </html>
  )
}
