name: It's time to wake up!
on:
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:
jobs:
  send_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send request
        run: |
          curl --request PATCH \
            --url "https://ihvlweakjvqmlibssjcu.supabase.co/rest/v1/isSleep?apikey=${{ secrets.SUPABASE_API_KEY }}&id=eq.1" \
            -H "Content-Type: application/json" \
            --data '{"id": "1"}'
        env:
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
